#!/bin/bash
# <UDF name="aegir_hostname" label="Enter Aegir hostname" example="aegir">
# <UDF name="aegir_domain" label="Enter Aegir domain" example="aegir.example.com">
# <UDF name="db_password" Label="MySQL root Password" />
# <UDF name="user_email" label="Enter your email to recieve a 1 time login link to Aegir" example="you@example.com">
# <UDF name="aegir_shell" label="Add a shell for the aegir user" oneOf="Yes,No" default="No">
# <UDF name="setup_acl" label="Setup ACL for Aegir directory" oneOf="Yes,No" default="No">

source <ssinclude StackScriptID="1">

function aegir_install {
	# install required packages
	apt-get -y install apache2 php5 php5-cli php5-mysql mysql-server postfix sudo git-core unzip curl expect
	
	# Get IP
	ipAddress=$(ifconfig | grep -m 1 'inet addr:' | cut -d: -f2 | awk '{ print $1}');
	# Insert IP and hostname and domain into /etc/hosts file
	sed -i '
/127.0.0.1 localhost/ a\
'"$ipAddress"' '"$AEGIR_HOSTNAME"' '"$AEGIR_DOMAIN"'
' /etc/hosts

  # Set hostname, just because
  hostname $AEGIR_HOSTNAME

	# create aegir user
        if [ "$AEGIR_SHELL" = "No" ]
	then 
	  adduser --system --group --home /var/aegir aegir
        else
          adduser --system --shell /bin/bash --group --home /var/aegir aegir
        fi
	adduser aegir www-data    #make aegir a user of group www-data

	# link aegir apache.conf into apache2/conf.d directory
	ln -s /var/aegir/config/apache.conf /etc/apache2/conf.d/aegir.conf
	
	# Get the aegir setup script and run it
	cd /tmp
	curl -L -o 'install.sh.txt' 'http://git.aegirproject.org/?p=provision.git;a=blob_plain;f=install.sh.txt;hb=provision-0.4-alpha11'
  curl -L -o 'automate_install.expect' 'http://github.com/dmp1ce/Linode-StackScript-for-Drupal-Aegir-hosting-system/raw/v3-alpha11/automate_install.expect'
	
  db_password_safe=$(replace_special_shell_characters $DB_PASSWORD)
  su -s /bin/sh aegir -c "expect automate_install.expect /tmp/install.sh.txt $AEGIR_HOSTNAME $USER_EMAIL $db_password_safe"

	# add aegir user to the sudoers file
	sed -i'-orig' '/# %sudo ALL=NOPASSWD: ALL/ a\
aegir ALL=NOPASSWD: /usr/sbin/apache2ctl' /etc/sudoers

	# enable cron tab for hosting service 
	# Can this script be run before Drupal setup?
	# su -s /bin/sh aegir
	# php /var/aegir/drush/drush.php --uri=http://aegir.$AEGIR_HOSTNAME.com hosting_setup

	# enable apache mode rewrite
	a2enmod rewrite
	# mark apache to restart                                                         
        touch /tmp/restart-apache2

	if [ "$SETUP_ACL" = "Yes" ]
	then
		# Using ACL setup guide here: http://www.debianhelp.co.uk/acl.htm
		apt-get install acl
		mount -o remount,acl /dev/xvda
		sed -i'-orig' 's/noatime,errors=remount-ro/acl,noatime,errors=remount-ro/' /etc/fstab

		# add Aegir group ACL permissions
		setfacl -R -m g:aegir:rwx /var/aegir
		setfacl -R -m d:g:aegir:rwx /var/aegir
	else 
		echo "Skipping ACL setup because of user preference."
		echo "setup_acl : $SETUP_ACL"
	fi
}

function replace_special_shell_characters () {
  # Replace ! $ \ characters with command line safe equivalent
  new_string=$1
  new_string=${new_string//!/\!}
  new_string=${new_string//$/\$}
  new_string=${new_string//\/\\}
  
  echo $new_string
}

system_update
postfix_install_loopback_only
mysql_install "$DB_PASSWORD" && mysql_tune 40
php_install_with_apache && php_tune
goodstuff
aegir_install
restartServices
